apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDW4otXNq5gyIEpKLaxD6isoXKcnOPXQQq9LMt/9j6XRxtW1wy36pkx8kX7w7U3MyBK1UWb2oGwnD5TnbXhOCjXmvtrf6fSYIAcBvGxXpYIFFAtc/P2wtkCFK+Dne57eEKxIY2nzOHps4X8rohD/tmnRueLsueTMQiNhj26uSz1LpZGZA+HyP2E933otfHKh1SGjEhuUqisKEIirMRaMhrkXVqLE9/hEveY8vjug0DXD9IWlzns2IFUQU1ff13hY368WDwoMhp+ckUM3hYaRxCOKwQyBKXeKo5odYneIk+b7TksefHYBylA0pCbbhVOXkx/hYUyXjOef0m1GevOLn2PZfFnIQJNF6TQ3fS64iIhhDFKCc3HkqGCYefcgENpmS1hbuBIsO4ANiXnGd8BH0ozw/yQw6FFDBtSXylRkHXphsdQzM4xhP5OvSuJeMxmA6b3hRpgp6UCvDTKr6Zw/ZDyUC5n6gDHNxu5QNqKmfAHH5RZ2R6kxPtLHv/e6tyHABjAnMLFUod7URg/Fwa48+M1hM28xhyw4MzZ3uf7TcuBzrFChU14lsTUUdh9pAf0v+vNuh5a3bVghfQ7IcWyyYhg0bJiaA8HtdizZsQo2+lwnGbgAU5dvrwndfRN9YYmLbdXOXhVxeZhghitOIecQb6AScuD7lR8Wu2jqALsCnk8X6uitoZZyuQcRzHHK+ys7JnY8WbjfwMHEu4E37itoCLvFwbLx1VNRqxOFrZe6ggxQOwBvZRimWcl
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

