apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA2CjLigygI9yUqtFsyBbYDuPqhxTub3D7ff6qRICuTGnvMkffkH/OXiat5hZni447rhKIowzo/k5/mqbokyf1eVZvOuZb4DOXXUZA05dJ7SHCim+KvUD3tNvUfaeO29DIt98DOR5NKfJuRNW965HRO22e4hF5fjt+Jk/QKUh1v75V+vKQk1RbkaO1FFJvPFEHF3cSfnteBnJpBJT0DbFdJdaFc8myeSsWjwPWUb2tdgs4xqsW8hNx73AwBQ/1sk1G21fnDMNjea+iWlExvf3iheji8JbQGzVz4i2+z+fvEHZBXL/8+JwzRC2SdwGmo7YQBxYE0TMvItR6TJYY7WHu6RGQW8l4msCOKTvtMp+DwAFAshuQR+rSgMZn4/z78nieDXik87vMTWrycWX5snaMQoHvrxCGVAfyRqSAi30zS20UpfmPM8O0/5df23IqFaJcc+wYKCEmgcnwpH33E4BcsTv0tg/PBomv3U0CM/0fEjZZJjJjrL3UgCNPRwCedgq8Md3vEoDoJ2MKaGzRsJHMVNc6CKBDn95lR0huMLdq+MV6Pzqf8WcMsD5CL+JK80GEVTLWYL2JiL6ki35Z8J8QAR2aOsfwsAhIan2pjzyVJLM4YRWG/VRL4Vek7p77hCL858huum942j6WnRiqpYeg8dxZS4550FzVJ4cW1A7mFrR/LvNdr7aK/9ZrSwQuTfHpbUUqn8Lw3LmkSMomCkSuRzasiDUxh/zcha8Ff0X3Ex+sJ3DmmUHwV
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

